/*
 * This Java source file was generated by the Gradle 'init' task.
 */
 import java.io.Console;
 import java.util.List;
 import java.util.Random;
 import java.util.ArrayList;
 import java.util.Arrays;
public class App {
    public static void main(String[] args) {
      List <String> words = Arrays.asList("one","house","car");
      Hangman randomWord= new Hangman();
      String word =randomWord.computedWord(words);
      randomWord.pickedWord= word;
      randomWord.output=randomWord.wordLength(word);
      String result ="";
      String[] resultSpit = randomWord.splitPickedWord(word);
      Console console = System.console();
      do {
        System.out.println(randomWord.output);
        System.out.println("Enter a letter");
        String character = console.readLine();
        result= randomWord.compareWords(resultSpit, character);
      } while (!word.equals(result));
    }
}
