/*
 * This Java source file was generated by the Gradle 'init' task.
 */
 import java.io.Console;
 import java.util.List;
 import java.util.Random;
 import java.util.ArrayList;
 import java.util.Arrays;
public class App {
    public static void main(String[] args) {
      List <String> words = Arrays.asList("one","house","car","glucose");
      Hangman randomWord= new Hangman();
      String word =randomWord.computedWord(words);
      randomWord.setPickedWord(word);
      randomWord.setOutput(randomWord.wordLength(word));
      String result ="";
      String[] resultSpit = randomWord.splitPickedWord(word);
      Console console = System.console();
      Boolean fail=false;
      int lifes=5;
      do {
        System.out.println(randomWord.getOutput());
        System.out.println("You have "+lifes+" lifes left");
        System.out.println("Enter a letter");
        String character = console.readLine();
        result= randomWord.compareWords(resultSpit, character);
        //if the word does not contain the entered character reduce lifes by one
        if (!word.contains(character)) {
          lifes=lifes-1;
        }
        //if the number oflifes reduces to 0 the game will end
        if(lifes ==0){
          fail =true;
        }

      } while (!word.equals(result)&& !fail);
    }
}
