/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;

public class HangmanTest {
  @Test
  public void checkIfWordIsRandomizing(){
  Hangman randomWord= new Hangman();
  List <String> words = Arrays.asList("one","house","car");
    String computed = randomWord.computedWord(words);
    assertTrue(computed,words.contains(computed));
  }
  @Test
  public void checkIfLengthOfWord(){
  Hangman randomWord= new Hangman();
  String expected= "----";
    assertEquals(expected,randomWord.wordLength("home"));
}
  @Test
  public void splitTheWordIntoAString(){
  Hangman randomWord= new Hangman();
    String[] expected ={"o","n","e"};
    assertEquals(expected,randomWord.splitPickedWord("one"));
  }
  // @Test
  // public void checkWheterTheLetterEnteredIsPartOfTheWord(){
  // Hangman randomWord= new Hangman();
  // String myWord="one";
  //   String expected ="-n-";
  //   assertEquals(expected,myWord.compareWords("n"));
  // }
}
